### PR TITLE
feat: included the adapter for ListView to display the objects info

### PR DESCRIPTION
**Pull request by vbouiller**
I added the class and layout required to have a neat and customizable list view from an arraylist of JSONObjects

### CODE REVIEW

**Comment by jsulpis** [comment]
@vbouiller I get errors on the ResultAdapter l.69 : Cannot resolve symbol 'ObjectInfoActivity' and the same next line with 'startActivity'. I don't know how adapters work so I cannot propose a solution, did you change anything after the last time you tested ?

**Comment by vbouiller** [comment]
Of course there's an error! Ahahah I remember why i did not commit just after I finished coding ;) 
Actually I added a onClickListener to every row of the list in order to start the activity 2. you mentioned in  the Android app specifications ;) 
So I need to code this activity so that when we click on a specified row, this activity appears with all the spec you defined! 
What do you think of this type of listing? It's very efficient because we just have to pass an array of JSONObject and everything is automated and rows are created, without using too much resource as it load only the rows showed on the screen - and reuses previous slots for new objects! (I could explain it further more if you want to!)

**Comment by jsulpis** [comment]
OK I got it. The ListView seems to be good, what you explained reminds me of a RecyclerView, it should be similar. I see also a layout row_result.xml which looks like what we could have in the activity you want to develop. Could you add this activity and link it to the elements of the list so that we have the layouts and we just need to fill the views with real data ?

**Comment by vbouiller** [comment]
Yes it works as a recycler view! 
Actually the row_result.xml is what is populated and inserted into the listView by the adapter.
What I'll do is create the activity 2. and add tot he intent the JSONObject - i'll see this with you tomorrow morning!

**Comment by vbouiller** [comment]
Should we merge this first? Then handle your branch ?
Because your pull request takes into account the modifications of this one... So it's pretty messy..

**Comment by jsulpis** [comment]
Well, we could either merge the two or only mine and close yours since as you said it is included in mine... I suggest you pull my branch and if it works fine you rebase the two (there should be no conflict)

**Pull request merged**
